### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by DrChat** [EXERift/EXERift#3]
Add a UI.
- Needs to be 3D, floating in front of the user. 2D will not work with the oculus!
- https://docs.unrealengine.com/latest/INT/Engine/UMG/UserGuide/index.html
- Render this to a texture and apply that texture to a surface in front of the user. May want an arch sort of shape to make it seem like a helmet or something

**Comment by bab178** [comment]
HUD is misaligned because not in 1080p see Warning
